### ISSUE TITLE
Add strong name

### ISSUE THREAD

**Issue by ImrePyhvel** [zone117x/MimeMapping#10]
Currently given library is missing a strong name signing and hence it cannot be referenced from strongly named libraries and projects. Currently, on build one gets warning:

> Warning	CS8002	Referenced assembly 'MimeMapping, Version=1.0.1.26, Culture=neutral, PublicKeyToken=null' does not have a strong name.

.. and in runtime this would fail with exception:

> Could not load file or assembly 'MimeMapping, Version=1.0.1.26, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)":"MimeMapping, Version=1.0.1.26, Culture=neutral, PublicKeyToken=null

Adding a strong name (with open key) would make the library usable for both signed and unsigned consumers.

**Comment by phxnsharp** [comment]
Just to be clear for everyone, by making the key "open" and publishing it in GitHub, there is no security provided by this strongly named dll. Anyone could now generate a trojan dll that looks the same as the signed one on NuGet and put it out there somewhere. I am not personally familiar with the proper technique for the code owners to create a private key and use that in their nightly build system for a public/oss project. There is [this](https://docs.microsoft.com/en-us/nuget/create-packages/sign-a-package) but that is about signing the nuget package, not the DLLs themselves.

**Comment by zone117x** [comment]
I could generate a private key and store it as a hidden env var in the CI that builds and publishes to nuget -- as opposed to having it committed publicly. But I'm not included to unless anyone is really interested..

**Comment by phxnsharp** [comment]
Thanks @zone117x. I don't personally need it.

**Comment by ImrePyhvel** [comment]
Strong name is not a security feature anymore (and for a long time), it's for identity. Like namespace, but with no real chance of conflict. So hiding it would serve no real purpose, just make it more cumbersome to work with.  MS recommendations as [described here](https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named):

> Do not rely on strong names for security. They provide a unique identity only.

and 

> If you are an open-source developer and you want the identity benefits of a strong-named assembly for better compatibility with .NET Framework, consider checking in the private key associated with an assembly to your source control system.
 
So, no CI magic is needed. All good.
