### ISSUE TITLE
Apache mime type list seems outdated. Why don't build this library on iana list?

### ISSUE THREAD

**Issue by cagianx** [zone117x/MimeMapping#15]
I notice I bring an example: I verified that sqlite is not even mentioned in the apache list. Moreover "recently" iana has changed the standard (https://stackoverflow.com/a/55071463) and has updated its list accordingly.

I understand that iana doesn't provide the list of extensions together with the mime, but at least you could be able to validate the mime type. So at least you could put this list next to the one used with the file extension.

What is your opinion about this?

thanks

**Comment by zone117x** [comment]
This library does not maintain its own database of mime types. See here for the data sources where mime types are pulled from: https://github.com/zone117x/MimeMapping/blob/master/KnownMimeTypes.tt

If you'd like to add new type(s) the options are:
1. Add them upstream to one of the existing sources used.
2. Open a PR that adds another data source that contains the mime types you want.
