### ISSUE TITLE
Add https://datatracker.ietf.org/doc/html/rfc7807 types

### ISSUE THREAD

**Issue by dzmitry-lahoda** [zone117x/MimeMapping#18]

**Comment by zone117x** [comment]
Can you please provide more information?

**Comment by dzmitry-lahoda** [comment]
add ProblemDetailsJson = "application/problem+json"

**Comment by zone117x** [comment]
This library is a mapping between file extensions and mime types. Again, please add more details such as a code snippet with the expected result. If the nearly empty responses continue then we might as well close this issue,

**Comment by dzmitry-lahoda** [comment]
no worries,also above mine type is part if iana list, so it is type not file extension. so it is mapping.
