### ISSUE TITLE
JFIF file type not mapped

### ISSUE THREAD

**Issue by nfgallimore** [zone117x/MimeMapping#3]
Could we add support for JFIF please?

**Comment by zone117x** [comment]
JFIF doesn't appear to be listed in either sources (nginx & apache) used to generate the map:  https://github.com/zone117x/MimeMapping/blob/master/KnownMimeTypes.tt#L16

**Comment by zone117x** [comment]
If you know if any other good file extension <-> MIME type databases to pull from that include this type then let me know, or even better, open a PR.
