### ISSUE TITLE
Pull in mime types from jshttp/mime-db project

### ISSUE THREAD

**Issue by zone117x** [zone117x/MimeMapping#8]
The popular js lib https://github.com/jshttp/mime-db has a community maintained list of extensions that are not represented in the existing sources. 

Specifically this file: https://github.com/jshttp/mime-db/blob/95e5d5d11bb55e5e107ed7503b37394f7d9ff8ac/src/custom-types.json

The templating/build engine should pull in the extensions from this source.

**Comment by Coderrob** [comment]
This is very relevant to my interests! The .mpd DASH manifest support is something I shimmed in to my own code that was missing from this package.

**Comment by Coderrob** [comment]
Add support to the TT for pulling from MimeDb. Pushed to PR https://github.com/zone117x/MimeMapping/pull/9
