### ISSUE TITLE
Refine the build targets

### ISSUE THREAD

**Issue by gintsk** [zone117x/MimeMapping#83]
Looking on our build targets it looks like:
`<TargetFrameworks>netstandard2.0;net461</TargetFrameworks>`

Can we drop `net461` as it is out-of-support? 
Should it be replaced by `net462` or can we just trim it? Are we using something useful from it?

**Comment by viceice** [comment]
please leave full net framework, i still need it on some sharepoint projects 🙃 

but we can raise it to `net462` as suggested by MS[^1]

[^1]: https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting

**Comment by gintsk** [comment]
Will pin it here, for future reference
> CONSIDER adding a target for `net462` when you're offering a `netstandard2.0` target.

>Using .NET Standard 2.0 from .NET Framework has some issues that were addressed in .NET Framework 4.7.2. You can improve the experience for developers that are still on .NET Framework 4.6.2 - 4.7.1 by offering them a binary that's built for .NET Framework 4.6.2.
