### ISSUE TITLE
Migrate to `System.Text.Json`

### ISSUE THREAD

**Issue by gintsk** [zone117x/MimeMapping#90]
Since `System.Text.Json` is part of .NET and we don't use specific `Newtonsoft.Json` functionality, it is easily possible to drop additional external dependency in favor of `System.Text.Json`

https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/migrate-from-newtonsoft?pivots=dotnet-8-0

**Comment by viceice** [comment]
You know that this is only a dev dependency and not a runtime dependency?

**Comment by gintsk** [comment]
Yes, I'm aware of the fact, it's build, test and T4 template dependency.

When generating from `KnownMimeTypes.tt` you can hit that kind of warnings:
`Multiple assembly references match 'Newtonsoft.Json' under Extensions directories.  Using 'C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\ENTERPRISE\COMMON7\IDE\EXTENSIONS\D5TXMLCD.SEK\Newtonsoft.Json.dll'.`

**Comment by viceice** [comment]
Why closed?
